### ISSUE TITLE
[PE-D][Tester A] Viewing an entity's details fails with valid view command format.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S2-CS2103T-T15-1/tp#159] opened 2023-03-31 19:00 UTC
To reproduce:

- Start up Reroll with default sample data.
- execute `view item Mike`
- Use `back` to leave edit mode.
- Then execute `view char Mike`

_With further inspection, the above failure to view an entity's details seems to produce the same bug even without an invalid view command being executed first._

The output is:

![image.png](https://raw.githubusercontent.com/NoyaRoeT/ped/main/files/767ac16e-6fd9-480c-912a-33335548924f.png)

and

![image.png](https://raw.githubusercontent.com/NoyaRoeT/ped/main/files/bea0443f-6a41-4a0c-9134-6d5f2de07efd.png)

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: NoyaRoeT/ped#7

**Comment by LeonardYam** [comment] 2023-04-06 14:18
Duplicate of #136

**Closed by LeonardYam** 2023-04-06 14:18 UTC
